### ISSUE TITLE
TypeError: this.api.start is not a function when type is 'proc'

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfsd-ctl#466] opened 2020-02-20 17:29 UTC
```
    "ipfs": "^0.41.1",
    "ipfsd-ctl": "^3.0.0"
```

```
(node:87572) UnhandledPromiseRejectionWarning: TypeError: this.api.id is not a function
    at Daemon.start (G:\Users\The Project\p2p\ws-ipfs\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:222:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```ts
import { createController } from 'ipfsd-ctl';

(async () => {
	let ipfsd = await createController({
		type: 'proc',
		ipfsModule: require('ipfs'),
		ipfsHttpModule: require('ipfs-http-client'),
		ipfsBin: require.resolve('ipfs/src/cli/bin.js'),
		ipfsOptions: {
			EXPERIMENTAL: {
				pubsub: true,
				ipnsPubsub: true,
				sharding: true,
				dht: true,
			},
			relay: {
				enabled: true,
				hop: {
					enabled: true
				}
			},
		},
		disposable: false,
	});


	await ipfsd.start();
	let ipfs = ipfsd.api;
	console.log(await ipfs.id())
})();
```

**Comment by hugomrdias** [comment] 2020-02-20 17:37
can you please give more context on this issue, format your code better and review the options you are passing they seems off.

**Comment by bluelovers** [comment] 2020-02-20 17:44
![image](https://user-images.githubusercontent.com/167966/74962862-affb8c00-544b-11ea-896a-5a4950d6d21a.png)

![image](https://user-images.githubusercontent.com/167966/74962884-b853c700-544b-11ea-93ac-adc302d5d36d.png)

**Comment by achingbrain** [comment] 2020-02-20 18:40
If you pass `disposable: false` you need to ensure the node is initialised and started before you use it, so you need to call `await ipfsd.init()` before calling `await ipfsd.start()`.

https://github.com/ipfs/js-ipfsd-ctl#disposable-vs-non-disposable-nodes

As a separate issue the `this.api.start is not a function` error will be fixed by https://github.com/ipfs/js-ipfs/pull/2762

**Comment by bluelovers** [comment] 2020-02-20 18:55
![image](https://user-images.githubusercontent.com/167966/74968332-a0814080-5455-11ea-9428-adecaa5408c7.png)


i add `await ipfsd.init()`

but still get `NotInitializedError: not initialized`

**Comment by achingbrain** [comment] 2020-02-20 19:23
It works for me like this, though I think there is an API regression here in that the `init`/`start` invocations are inconsistent:

```javascript
const { createController } = require('ipfsd-ctl');

(async () => {
	let ipfsd = await createController({
		type: 'proc',
		ipfsModule: require('ipfs'),
		ipfsOptions: {
			init: true,
			EXPERIMENTAL: {
				pubsub: true,
				ipnsPubsub: true,
				sharding: true,
				dht: true,
			},
			relay: {
				enabled: true,
				hop: {
					enabled: true
				}
			},
		},
		disposable: false
	});

	await ipfsd.start();
	let ipfs = ipfsd.api;
	console.log(await ipfs.id())
})();

```

**Closed** 2020-02-22 10:17 UTC
