### ISSUE TITLE
sometime ipfs api file didn't delete when server stoped

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfsd-ctl#468] opened 2020-02-22 09:59 UTC
when `IPFD_PATH/api` file exists, Controller will never start and throw error

hope can fix this

the code for how i avoid this, but hope can have build-in way fix this
https://github.com/bluelovers/ws-ipfs/blob/master/packages/use-ipfs/lib/ctl.ts

**Comment by hugomrdias** [comment] 2020-03-15 11:45
why are starting a new ipfs-http-client ? i really don't understand the situation , can explain further?

**Comment by bluelovers** [comment] 2020-03-15 17:33
it for test ipds is running or not

**Comment by hugomrdias** [comment] 2020-03-15 17:35
i dont understand what you mean

**Comment by bluelovers** [comment] 2020-03-15 23:05
hmm... i think u just need understand 

`IPFD_PATH/api` sometime didn't delete when ipfs is stop
it make `js-ipfsd-ctl` can't start ipfs

don't care how i try avoid this happen

my point only

1. check `IPFD_PATH/api` is exists or not
2. if it exists, check ipfs is running or not
3. if ipfs is not running, delete `IPFD_PATH/api`
4. start ipfs

**Comment by hugomrdias** [comment] 2020-03-16 09:25
I cannot reproduce this, just think about it the tests wouldn't work if this happened, ipfs tests use ctl would not work also, ipfs-http-client tests would not work.
Either you can produce a **minimal** repo where this happens or I'm gonna close this issue.

**Comment by bluelovers** [comment] 2020-03-16 11:04
it is random happen

**Closed** 2020-04-20 14:48 UTC
